### PR TITLE
Change links to open desktop application.

### LINKED ISSUE #110: Change links to open desktop application
### Please agree to the following

- [x] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [x] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Use katta scheme

### System Setup

```markdown
Change `x-katta-action:katta`usages to `katta://hub.domain/(basepath)/`. Remove any query parameters.

Example: `katta://testing.katta.cloud/shift7`.
```

### Steps to Reproduce

The `katta:` scheme is registered from the desktop application.

### Expected Behavior

- [ ] Window opened in File Explorer for open connection.
- [ ] Connection prompt when no matching bookmark is found with _Server_ prefilled.

### Actual Behavior

Current URI format not handled.

### Reproducibility

Always

### Relevant Log Output

```shell

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenkins**
Fixes #110

### CODE REVIEW

File: frontend/src/components/CreateVault.vue [hunk 1]
```diff
@@ -1315,7 +1315,7 @@ async function downloadVaultTemplate() {
 async function openBookmark() {
   onOpenBookmarkError.value = null;
   try {
-    window.location.href = `x-cipherduck-action:cipherduck?url=${encodeURIComponent(document.baseURI)}`;
+    window.location.href = `katta://${new URL(absBackendBaseURL).host + new URL(absBackendBaseURL).pathname}`;
```
Comment (chenkins) [inline frontend/src/components/CreateVault.vue]: must not include `/api` part

**Review by dkocher — APPROVED** [review]
